name: 
author:
url: 
baseurl: ""
resume_site: 
description: Selamat datang di web LKP MultiSklill!
github_username: rafi-sudo
github: 
plugins: []
permalink: /:year-:month-:day-:title
paginate: 
paginate_path: 
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
markdown: kramdown
comments :
  gitalk :
    clientID : 
    clientSecret : 
    repo : 
    owner : rafi-sudo
    admin : gardisbanjartwo
