[build]
  publish = "_site"
  command = "bundle exec jekyll build"

[build.environment]
  RUBY_VERSION = "3.2.2" # atau yang cocok dengan versi Jekyll kamu
  JEKYLL_ENV = "production"

[context.production.environment]
  JEKYLL_ENV = "production"
