backend:
  name: git-gateway
  branch: deploying  # Ganti kalau branch kamu bukan 'main'

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Blogging"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  
  - name: "Information"
    label: "info-pengumuman"
    folder: "_posts/informasi"
    create : true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  
  - name: "kursus-desain"
    label: "deskripsi-vokasi"
    file: "kursus-desain.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "kursus-komputer"
    label: "deskripsi-vokasi"
    file: "kursus-komputer.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "kursus-mengemudi"
    label: "deskripsi-vokasi"
    file: "kursus-mengemudi.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "kursus-menjahit"
    label: "deskripsi-vokasi"
    file: "kursus-menjahit.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "program-kursus"
  - label: "list program kursus gratis"
  - file: "programkursus.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "tentang"
  - label: "berisi visi misi legalitas"
  - file: "tentang.md"
  - fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  

  - name: "paket-kursus"
  - label: "list paket paket kursus dari termurah"
  - file: "paketkursus.md"
    file: "kursus-desain.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }